plugins {
    id 'application'
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

group "dev.moetz.deaddrop"
version "0.0.1"

application {
    mainClass = 'dev.moetz.deaddrop.ApplicationKt'
}

kotlin {
    jvmToolchain(21)
}

repositories {
    mavenCentral()
}

dependencies {
    implementation Ktor.server.core
    implementation Ktor.server.netty
    implementation Ktor.server.htmlBuilder
    implementation KotlinX.serialization.json
    implementation 'io.ktor:ktor-server-default-headers-jvm:_'
    implementation 'io.ktor:ktor-server-auto-head-response-jvm:_'
    implementation 'io.ktor:ktor-server-caching-headers-jvm:_'
    implementation 'io.ktor:ktor-server-forwarded-header-jvm:_'
    implementation 'io.ktor:ktor-server-conditional-headers-jvm:_'
    implementation 'io.ktor:ktor-server-compression-jvm:_'

    implementation "ch.qos.logback:logback-classic:_"

    testImplementation "io.ktor:ktor-server-tests:_"
    testImplementation Kotlin.test
    testImplementation Testing.mockK
}

jar {
    manifest {
        attributes['Main-Class'] = 'dev.moetz.deaddrop.ApplicationKt'
        attributes['Implementation-Title'] = "DeadDrop"
        attributes['Implementation-Version'] = archiveVersion
    }
}
